In [1]:
# Generate a 3x3 matrix of random numbers using NumPy.

import numpy as np

# Generate a 3x3 matrix of random floats between 0 and 1
print("3x3 matrix of random floats between 0 and 1")

matrix = np.random.rand(3,3)
print(matrix)

# 3x3 matrix with integers between 1 and 10
print("\n\n3x3 matrix with integers between 1 and 10")
int_matrix = np.random.randint(1, 11, size=(3,3))
print(int_matrix)

# 3x3 matrix from a standard normal distribution
print("\n\n3x3 matrix from a standard normal distribution")
normal_matrix = np.random.randn(3,3)
print(normal_matrix)


3x3 matrix of random floats between 0 and 1
[[0.56159011 0.93743312 0.71872833]
 [0.66418822 0.80144621 0.36179086]
 [0.70927545 0.82316686 0.9626753 ]]


3x3 matrix with integers between 1 and 10
[[10  5  9]
 [ 9  4  1]
 [10  4  9]]


3x3 matrix from a standard normal distribution
[[ 1.66269212 -0.67758009 -0.22501831]
 [ 0.10459843 -0.04686857  1.1655684 ]
 [-1.41200541  0.18630817  0.9641858 ]]
