In [5]:
# Array broadcasting in numpy allows to perform operations on different arrays which are of different shapes.
# Rule for broadcasting is 
#   Either number of rows of arrays match or one value being 1
#   Either number of columns of arrays match or one value being 1
#
# Broadcasting allows numpy to perform operations on arrays with different shapes by virtually expanding dimensions so that 
# they match larger arrays shape
import numpy as np
array_1 = np.array([[1, 2, 3, 4]])
array_2 = np.array([[1], [2], [3], [4]])
print(array_1.shape)
print(array_2.shape)

(1, 4)
(4, 1)


In [7]:
# In the above example, 
#   number of rows for array_1 and array_2 not matching. But one of them is 1. So it eligible for broadcasting
#   number of columns for array_1 and array_2 not matching. But one of them is 1. So it eligible for broadcasting

# so if add these 2 arrays we will get a (4,4) array
result = array_1 + array_2
print(result)

[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]]


In [10]:
# Now lets say we defined our arrays as
import numpy as np
array_1 = np.array([[1, 2, 3, 4],[5, 6, 7,8]])
array_2 = np.array([[1], [2], [3], [4]])
print(array_1.shape)
print(array_2.shape)

(2, 4)
(4, 1)


In [13]:
# In the above example, 
#  number of rows of arrays is 2 and 4 for array_1 and array_2 respectively. Which is not equal or one of them is one.
#  So these 2 arrays are not compatible even if column count condition satisfies
result = array_1 + array_2
print(result)

ValueError: operands could not be broadcast together with shapes (2,4) (4,1) 

In [16]:
# Does an array and a scalar value broadcast ?
import numpy as np
array_1 = np.array([1, 2, 3, 4])
array_2 = 2
result = array_1 + array_2
print(result)

[3 4 5 6]


In [21]:
# In the above example, it first calculate the spape of array_1, which will be (4,)
# array_2 is a scalar value so when it operates with an array it treats scalar as array with dimension (1,). 
# That means internally it will expand as [2]
# So rule match like this
# number of rows are not matching but one of them is 1
# number of columns are equal
print(array_1.shape)

(4,)


In [22]:
# Example of multiplication table
import numpy as np
array_1 = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])
array_2 = np.array([[1], [2], [3], [4], [5], [6], [7], [8], [9], [10]])
result = array_1 * array_2
print(result)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]
