In [2]:
# There are different arithmetic operations can be performed using Numpy
# 1) Scalar Arithmetic
# 2) Arithmetic using vector math functions
# 3) Element-wise arithmetic
# 4) Comparison arithmetic


In [4]:
# Scalar Arithmetic
import numpy as np

array = np.array([1, 2, 3, 4])
print(array + 1)
print(array * 2)
print(array - 1)
print(array / 2)
print(array ** 2)

[2 3 4 5]
[2 4 6 8]
[0 1 2 3]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]


In [15]:
# Arithmetic using vector math functions

import numpy as np

array = np.array([4, 9, 16, 25])
print(np.sqrt(array))

# Examples of mathematical constants defined in numpy
print(np.pi)

[2. 3. 4. 5.]
3.141592653589793


In [18]:
# Element-wise arithmetic

import numpy as np

array_1 = np.array([2, 3, 5 ,7])
array_2 = np.array([10, 11, 12, 13])

print(array_1 + array_2)
print(array_1 - array_2)
print(array_1 * array_2)
print(array_1 / array_2)
print(array_1 ** array_2)

[12 14 17 20]
[-8 -8 -7 -6]
[20 33 60 91]
[0.2        0.27272727 0.41666667 0.53846154]
[       1024      177147   244140625 96889010407]


In [20]:
# Comparison Arithmetic
# With this arithmetic we can create boolean arrays

import numpy as np
marks = np.array([95, 65, 58, 85, 74, 100])
print(marks > 65)

[ True False False  True  True  True]


In [22]:
print(marks <= 65)

[False  True  True False False False]


In [24]:
marks = np.array([95, 65, 58, 85, 74, 100])
marks[marks < 65] = 0
print(marks)

[ 95  65   0  85  74 100]


In [34]:
# Similarly
marks = np.array([95, 65, 58, 85, 74, 100])
marks[marks > 65] = 1
print(marks)

[ 1 65 58  1  1  1]
