In [2]:
# Numpy is used for building and manipulating N dimensional arrays. Numpy is short form is Numerical Python
# Numpy is a python module which is wrapper module for calling c based numpy module.
# Python list is slower when compared to Numpy arrays

import numpy as np

array_1 = np.array([1,2,3,4])
print(array_1)

[1 2 3 4]


In [4]:
array = np.array('A')
print(array)

A


In [5]:
array = np.array([[1,2,3],[4,5,6]])
print(array)

[[1 2 3]
 [4 5 6]]


In [8]:
array = np.array([[[1, 2, 3, 4]], [[5, 6, 7, 8]]])
print(array)

[[[1 2 3 4]]

 [[5 6 7 8]]]
