In [8]:
# Given a 10X10 matrix of ones, change all the interior values (not on the border) to 0.
import numpy as np

array = np.ones((10,10), dtype=int)
print(array)
print('--------------------------------')
array[1:-1,1:-1] = 0 # 1:Starts the selection at the second row/column (skipping the first border).
                     # -1: Ends the selection just before the last row/column (skipping the last border).
print(array)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]
--------------------------------
[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [15]:
# Create a 5X5 matrix with values ranging from 0 to 24 and extract the second and fourth rows.
import numpy as np

array = np.arange(0,25)
print(array)
print('------------------------------------------------')
array_5X5 = array.reshape(5,5)
print(array_5X5)
print('------------------------------------------------')
print(f'Second Row: {array_5X5[1]}')
print(f'Fourth Row: {array_5X5[3]}')

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
------------------------------------------------
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
------------------------------------------------
Second Row: [5 6 7 8 9]
Fourth Row: [15 16 17 18 19]


In [22]:
# Create a random 1D array of size 20. 
# Replace all values greater than 0.5 with 1 and all values less than or equal to 0.5 with 0.
import numpy as np

random_array = np.random.rand(20)
print(random_array)
print('-------------------------------------------------')

# Replace values > 0.5 with 1 and values <= 0.5 with 0
processed_array = np.where(random_array > 0.5, 1, 0)
print("\nProcessed Array:")
print(processed_array)

[0.88545292 0.13950177 0.76905486 0.17906373 0.32610477 0.56294641
 0.08164416 0.34838129 0.99693481 0.85590136 0.78635628 0.18247446
 0.37624746 0.43707319 0.89452857 0.80725531 0.81721388 0.95258322
 0.28102929 0.17856096]
-------------------------------------------------

Processed Array:
[1 0 1 0 0 1 0 0 1 1 1 0 0 0 1 1 1 1 0 0]
