In [10]:
# Convert a 2D array into a 1D array without using .flatten()
import numpy as np

array = np.array([[1,2,3,4], [5,6,7,8]])
print(array)
print('-----------------------------------------')
print(array.flatten())


[[1 2 3 4]
 [5 6 7 8]]
-----------------------------------------
[1 2 3 4 5 6 7 8]


In [17]:
# Create a random vector of size 10 and sort it in ascending order.
import numpy as np

# Create a random vector of size 10
vector = np.random.rand(10)
print(f'Original Vector:\n{vector}\n')

# Sort the vector in ascending order
sorted_vector = np.sort(vector)

print("Ascending Sorted Vector:\n", sorted_vector)

Original Vector:
[0.02951082 0.92927425 0.14845944 0.98655293 0.33500877 0.51528188
 0.78566646 0.03343386 0.78548932 0.990097  ]

Ascending Sorted Vector:
 [0.02951082 0.03343386 0.14845944 0.33500877 0.51528188 0.78548932
 0.78566646 0.92927425 0.98655293 0.990097  ]


In [19]:
# Create a random vector of size 10 and sort it in descending order.
import numpy as np

# Create a random vector of size 10
vector = np.random.rand(10)
print(f'Original Vector:\n{vector}\n')

# Sort the vector in ascending order
sorted_vector = np.sort(vector)

print("Descending Sorted Vector:\n", sorted_vector[::-1])

Original Vector:
[0.75971357 0.08972859 0.27449671 0.11267253 0.03921125 0.2508255
 0.0183872  0.57892369 0.9772241  0.81585377]

Descending Sorted Vector:
 [0.9772241  0.81585377 0.75971357 0.57892369 0.27449671 0.2508255
 0.11267253 0.08972859 0.03921125 0.0183872 ]


In [24]:
# Given a 1D array and a scalar value, find the value in the array that is closest to the scalar.
import numpy as np

def find_closest(arr, scalar):
    # Convert to numpy array if it isn't one already
    arr = np.asarray(arr)
    
    # Find the index of the minimum absolute difference
    # This subtracts the scalar from every element and takes the absolute value, 
    # giving you the "distance" of each element from the target.
    # .argmin(): This returns the index of the smallest value in that "distance" array.
    idx = (np.abs(arr - scalar)).argmin()
    
    return arr[idx]

# Example
data = np.array([10, 22, 38, 45, 75])
target = 40

result = find_closest(data, target)
print(f"The value closest to {target} is {result}")

The value closest to 40 is 38


In [37]:
# Compute the moving average of a 1D array using a window size of n=3
import numpy as np

def moving_average(a, n=3):
    # Method using cumulative sums for speed
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

# Sample 1D array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
n = 3

result = moving_average(arr, n)

print(f"Original Array: {arr}")
print(f"Moving Average: {result}\n")
print('''A moving average (also known as a rolling or running average) is a statistical calculation used to analyze data points 
by creating a series of averages of different subsets of the full data set. 
     Its primary purpose is to smooth out short-term fluctuations and highlight longer-term trends or cycles.
     So Instead of calculating a single average for an entire list of numbers, you move a "window" of a fixed size (n)
     across the data. 
     For each step, you calculate the average of the numbers currently inside that window.\n''')
print('How it works (for n=3):\nFirst window: (1+2+3)/3 = 2.0\nSecond window: (2+3+4)/3 = 3.0\nThird window: (3+4+5) / 3 = 4.0\n...and so on.')

Original Array: [ 1  2  3  4  5  6  7  8  9 10]
Moving Average: [2. 3. 4. 5. 6. 7. 8. 9.]

A moving average (also known as a rolling or running average) is a statistical calculation used to analyze data points 
by creating a series of averages of different subsets of the full data set. 
     Its primary purpose is to smooth out short-term fluctuations and highlight longer-term trends or cycles.
     So Instead of calculating a single average for an entire list of numbers, you move a "window" of a fixed size (n)
     across the data. 
     For each step, you calculate the average of the numbers currently inside that window.

How it works (for n=3):
First window: (1+2+3)/3 = 2.0
Second window: (2+3+4)/3 = 3.0
Third window: (3+4+5) / 3 = 4.0
...and so on.


In [38]:
# Find the unique values and their counts in an array of integers.
import numpy as np

# Sample array
arr = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 1, 2])

# Get unique values and their frequencies
unique_values, counts = np.unique(arr, return_counts=True)

# Combine them for a clear view
result = dict(zip(unique_values, counts))

print("Unique Values:", unique_values)
print("Counts:", counts)
print("Summary:", result)

Unique Values: [1 2 3 4 5]
Counts: [2 3 3 4 1]
Summary: {1: 2, 2: 3, 3: 3, 4: 4, 5: 1}
