In [2]:
# Create a 5X3 matrix and a 3X2 matrix. Compute their dot product.
# Note: To compute the dot product of two matrices, the number of columns in the first matrix must match 
#       the number of rows in the second matrix
import numpy as np

# Create a 5x3 matrix
matrix_A = np.random.randint(0, 10, (5, 3))

# Create a 3x2 matrix
matrix_B = np.random.randint(0, 10, (3, 2))

# Compute the dot product
result = np.dot(matrix_A, matrix_B)

print("Matrix A:\n", matrix_A)
print("Matrix B:\n", matrix_B)
print("Dot Product:\n", result)

Matrix A:
 [[6 3 8]
 [3 6 5]
 [0 5 8]
 [9 2 6]
 [6 7 4]]
Matrix B:
 [[8 7]
 [8 5]
 [2 8]]
Dot Product:
 [[ 88 121]
 [ 82  91]
 [ 56  89]
 [100 121]
 [112 109]]


In [5]:
# Given two arrays A and B, find the indices where the elements are equal.
import numpy as np

A = np.array([1, 2, 3, 4, 5, 8])
B = np.array([1, 0, 3, 4, 2, 8])

matching_indices = np.where(A == B)[0]
print(f'Matching Indices: {matching_indices}')

Matching Indices: [0 2 3 5]


In [16]:
# Create a random array and normalize it (subtract the mean and divide by the standard deviation).
# To normalize an array, you shift its mean to 0 and scale its standard deviation to 1. 
# This is a common preprocessing step in machine learning and data analysis.

import numpy as np

# Create a random 1D array
random_array = np.random.rand(10)

# Calculate mean and standard deviation
mean = np.mean(random_array)
std_dev = np.std(random_array)
print(f'Mean of original array: {mean}')
print(f'Standard Deviation of original array: {std_dev}\n')

# Normalize the array
normalized_array = (random_array - mean) / std_dev

print(f"Original Array: {random_array}\n")
print(f"Normalized Array: {normalized_array}\n")

print(f'Mean of Normalized Array: {np.round(np.mean(normalized_array), 10)}')
print(f'Standard Deviation of Normalized Array: {np.round(np.std(normalized_array), 10)}')



Mean of original array: 0.46834791239168255
Standard Deviation of original array: 0.2455890614709735

Original Array: [0.24134514 0.10965561 0.25175794 0.34807043 0.79150321 0.66017888
 0.28395929 0.67878227 0.84522945 0.47299691]

Normalized Array: [-0.92431955 -1.46053859 -0.88192029 -0.48975098  1.3158375   0.7811055
 -0.75080146  0.85685558  1.53460228  0.01893   ]

Mean of Normalized Array: -0.0
Standard Deviation of Normalized Array: 1.0
