In [1]:
# Numpy Shape
# Numpy shape gives 2 information 
#   a) Number of rows
#   b) Number of elements in each row
#  So output will be a tuple as (<no.of.rows>, <no.of.elements.in.each.row>)
#  Note:
#     If <no.of.rows> = 1, then shape will be (<no.of.elements.in.each.row>, )

import numpy as np
array_1 = np.array('A')
print(array_1.shape) # will print (), that means no shape

array_2 = np.array([1,2,3,4])
print(array_2.shape) # This will print (4,). That means its a 1D array
# Note: In Numpy, ID arrays is orientation-less. That means it doesnt posses the concept of being 'row' or 'column'. 
#       It is simply a sequence of elements in single dimension. 
#       So most of us will expect the shape as (1, 4). But in Numpy such array will be represented using np.array([[1,2,3,4]])

array_3 = np.array([[1,2,3,4]])
print(array_3.shape) # This will print (1,4)

array_4 = np.array([])
print(array_4.shape) # This will print (0,). This means 1D array with zero elements

array_5 = np.array([ [[1, 2, 3]], [[4, 5, 6]] ])
print(array_5.shape) # This will print as (2, 1 ,3). Meaning it has 2 levels and each level has one row and each row has 3 columns

array_6 = np.array([ [[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]] ])
print(array_6.shape) # This will print as (2, 2 ,3). Meaning it has 2 levels and each level has 2 row and each row has 3 columns

array_7 = np.array([ [[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]] ])
print(array_7.shape) # This will print as (2, 3 ,3). Meaning it has 2 levels and each level has 3 row and each row has 3 columns

()
(4,)
(1, 4)
(0,)
(2, 1, 3)
(2, 2, 3)
(2, 3, 3)


In [8]:
# Creating empty array
# empty() of numpy is used to create a new array of a specific shape and type without initializing its entries.
# You will see random values contained in array but that will be whatever data was already sitting in those 
# memory locations (often referred to as "garbage" or "uninitialized" data). 
# You should not use the values in an "empty" array until you have manually assigned them.
# Basically empty() will create an array of specified shape but no value initialization is done as zeros() or ones().
array_1 = np.empty((6,0))  # This will create a empty array as its one dimension is 0
print(array_1)
array_2 = np.empty((0,6))  # This will create a empty array as its one dimension is 0
print(array_2)
array_3 = np.empty((1,4)) # By default data type of the element will be float. 
                          # Values appearing in array is not initialized but its the older value present 
                          # in that memory locatiom.
print(array_3)
array_3 = np.empty((1,4), dtype=int)
print(array_3)

[]
[]
[[4.9e-324 9.9e-324 1.5e-323 2.0e-323]]
[[1 2 3 4]]


In [13]:
# Initializing array using zeroes
array_4 = np.zeros((2,2))
print(array_4)
array_5 = np.zeros((2,2), dtype=int)
print(array_5)

[[0. 0.]
 [0. 0.]]
[[0 0]
 [0 0]]


In [21]:
# Create a function which will initialize the NXN array with a given number
import numpy as np
def fill_array(shape, number):
    array = np.zeros(shape, dtype=int)
    return array + number

array = fill_array((2,3), 7)
print(array)

[[7 7 7]
 [7 7 7]]


In [20]:
# Numpy has a method named full() which does the same functionality of fill_array
import numpy as np
array = np.full((2,3), 7)
print(array)

[[7 7 7]
 [7 7 7]]


In [24]:
# arange() - This function is used for filling the array with a range of values
# arange(start, stop, step)
import numpy as np
array = np.arange(1,10)
print(array)
array = np.arange(1,10,2)
print(array)

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [29]:
# reshape() - This function is used for reshaping an array
import numpy as np
array = np.array([[1,2,3,4], [4,5,6,7]])
print(f'Orignal Array Shape: {array.shape}')
reshaped = np.reshape(array, (4,2))
print(reshaped)
print(f'Reshaped Array Shape: {reshaped.shape}')

Orignal Array Shape: (2, 4)
[[1 2]
 [3 4]
 [4 5]
 [6 7]]
Reshaped Array Shape: (4, 2)


In [32]:
# flatten() - This method is used to flatten an array
import numpy as np
array = np.array([[1,2,3,4],[5,6,7,8]])
print(array)
flatten = array.flatten()
print(flatten)

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]
