In [2]:
# Create a 3X3 identity matrix.
# In linear algebra, an identity matrix is a square matrix with ones on the main diagonal and zeros everywhere else.
import numpy as np

identity_3X3 = np.eye(3)
print(identity_3X3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
# Create a 1D array of numbers from 10 to 49
import numpy as np

range_generator = np.random.default_rng(seed=10)
array  = np.array(range_generator.integers(10,50, size=(40,))) # this method can contain repeated elements
print(array)
print('------------------------------------------------')
# We also can use arange()
array = np.arange(10, 50)
print(array)

[41 48 20 18 41 43 30 15 43 30 16 15 26 37 26 43 10 27 30 48 19 43 12 23
 39 33 47 40 46 43 15 47 43 15 49 39 22 15 25 46]
------------------------------------------------
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [22]:
# Reverse a vector or numpy array
import numpy as np

array = np.arange(10, 50)
reverse_1 = array[::-1]
print(reverse_1) # Fastest
print('--------------------------------------------------')
reverse_2 = np.flip(array)
print(reverse_2)
print('--------------------------------------------------')
reverse_3 = np.flipud(array)
print(reverse_3)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
--------------------------------------------------
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
--------------------------------------------------
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [27]:
# Create an 8 X 8 matrix and fill it with a checkerboard pattern (alternating 0s and 1s).
import numpy as np

# 1. Initialize an 8x8 matrix of zeros
checkerboard = np.zeros((8, 8), dtype=int)
print(checkerboard)
print('--------------------------------------')

# 2. Fill specific rows and columns with 1s
# Pattern: [start_index:end_index:step]

# Target rows 1, 3, 5, 7 and columns 0, 2, 4, 6
checkerboard[1::2, ::2] = 1
print(checkerboard)
print('--------------------------------------')

# Target rows 0, 2, 4, 6 and columns 1, 3, 5, 7
checkerboard[::2, 1::2] = 1

print(checkerboard)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
--------------------------------------
[[0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]]
--------------------------------------
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [29]:
# Create an 8 X 8 matrix and fill it with a checkerboard pattern (alternating 0s and 1s) using tile()
block = np.array([[0, 1], [1, 0]])
checkerboard = np.tile(block, (4, 4))
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [31]:
# Create a 5X5 array with random values
import numpy as np

range_generator = np.random.default_rng(seed=10)
array  = np.array(range_generator.integers(1,50, size=(5,5))) # this method can contain repeated elements
print(array)

[[39 47 13 11 39]
 [41 26  8 41 26]
 [ 8  7 21 34 20]
 [42  1 21 26 47]
 [12 41  4 17 37]]


In [35]:
# Create a 5X5 array with random values sampled from a standard normal distribution.
import numpy as np

rng = np.random.default_rng()
array = rng.standard_normal((5,5))
print(array)

[[ 1.03909828  0.56366284  1.45178287  0.37881891 -0.32944501]
 [-0.57636525 -0.5999283  -0.51425627  0.06130551  0.61825664]
 [-0.6375391   0.85263479 -0.58539335 -1.5625513   0.94683723]
 [ 0.27188825  0.15044045 -1.32761629  1.08378524 -1.39325387]
 [-0.62075836 -0.87178878  1.51550278 -0.2823441   0.49866107]]


In [45]:
# Create 5X3 matrix
import numpy as np

print('Method 1')
array = np.arange(15).reshape(5,3)
print(array)
print('---------------------------------------')
print('Method 2')
array = np.random.randint(0, 10, (5, 3)) # Number range from 0 - 9
print(array)

Method 1
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
---------------------------------------
Method 2
[[3 2 9]
 [1 9 0]
 [2 1 5]
 [3 4 1]
 [3 2 8]]


In [44]:
# Create a 3X2 matrix

print('Method 1')
array = np.arange(6).reshape(3,2)
print(array)
print('---------------------------------------')
print('Method 2') 
array = np.random.randint(0, 10, (3, 2)) # Number range from 0 - 9
print(array)

Method 1
[[0 1]
 [2 3]
 [4 5]]
---------------------------------------
Method 2
[[2 6]
 [1 1]
 [8 9]]
