In [2]:
# Array slicing in Numpy
# Numpy arrays can be sliced in 2 ways
# 1) Row slicing
#     Format will be array[start:end:step]
# 2) Column slicing
#     Format will be array[start:end:step, start:end:step]
#     First range represents row and second represents column

# Row slicing
import numpy as np
array = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])
print(array[0:2])

[[1 2 3 4]
 [5 6 7 8]]


In [4]:
print(array[0:5:2])

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [6]:
print(array[::1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [8]:
print(array[::-1])

[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [10]:
print(array[::-2])

[[13 14 15 16]
 [ 5  6  7  8]]


In [13]:
# Column Slicing
import numpy as np
array = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])
print(array[:,0:2])

[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]


In [15]:
print(array[:,0:5])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [18]:
print(array[:,::-1])

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


In [20]:
print(array[0:2,0:2])

[[1 2]
 [5 6]]


In [23]:
print(array[0:5:2,0:2])

[[ 1  2]
 [ 9 10]]


In [25]:
print(array[0:5:2,0:5:2])

[[ 1  3]
 [ 9 11]]


In [27]:
print(array[:,-1:-5:-1])

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


In [29]:
print(array[::-1,-1:-5:-1])

[[16 15 14 13]
 [12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]
