In [3]:
# Numpy can be used to generate random dataset
import numpy as np

range_generator = np.random.default_rng()
print(range_generator) # Its a generator

Generator(PCG64)


In [27]:
# Generating random integers
import numpy as np

range_generator = np.random.default_rng()
print(range_generator.integers(1,7))
print('--------------------------------')
print(range_generator.integers(low=2, high=9))
print('--------------------------------')
print(range_generator.integers(3,8, size=3))
print('--------------------------------')
print(range_generator.integers(3,8, size=(3,2)))

3
--------------------------------
2
--------------------------------
[4 5 3]
--------------------------------
[[4 7]
 [5 4]
 [7 7]]


In [31]:
# Setting seed for generating random numbers
# When seed is set then it will generate the same numbers
import numpy as np

range_generator = np.random.default_rng(seed=5)
array = np.array([10, 5, 4, 8, 11, 23, 27, 30, 45])
print(range_generator.integers(1, 10, size=3))
print(range_generator.integers(1, 10, size=3))
print(range_generator.integers(1, 10, size=3))
print("-------------------------------------------")
# Reason why different print gives different result is because we are using same range_generator for all 3 prints.
# So once a seed is set, then it will give different numbers every time we generate numbers. If we want same result every time,
# then we need to intiate the generator every time with same seed like below
range_generator = np.random.default_rng(seed=5)
print(range_generator.integers(1, 10, size=3))
range_generator = np.random.default_rng(seed=5)
print(range_generator.integers(1, 10, size=3))
range_generator = np.random.default_rng(seed=5)
print(range_generator.integers(1, 10, size=3))


[7 8 1]
[8 5 5]
[6 3 9]
-------------------------------------------
[7 8 1]
[7 8 1]
[7 8 1]


In [44]:
# Generating random floating point numbers
import numpy as np

random_number = np.random.uniform()
print(random_number)
print('------------------------------')
random_number = np.random.uniform(-1, 1)
print(random_number)
print('------------------------------')
random_number = np.random.uniform(low=-1, high=1)
print(random_number)
print('------------------------------')
random_numbers = np.random.uniform(-1, 1, size=3)
print(random_numbers)
print('------------------------------')
random_array = np.random.uniform(-1, 1, size=(3,2))
print(random_array)                

0.04911549268457149
------------------------------
0.638873505087558
------------------------------
0.25387786039090665
------------------------------
[ 0.52020568 -0.58926994  0.12115433]
------------------------------
[[-0.10664713  0.02589425]
 [ 0.18371296  0.73855424]
 [-0.25151531 -0.5444768 ]]


In [50]:
# Setting seed for generating random numbers
# Similarly as in integers if we want same number to be generated then we have to reinitiate the seed() 
import numpy as np

np.random.seed(seed=5)
random_number = np.random.uniform()
print(random_number)
print('------------------------------')
random_number = np.random.uniform()
print(random_number)
print('------------------------------')
random_number = np.random.uniform(-1, 1)
print(random_number)
print('------------------------------')
random_number = np.random.uniform(low=-1, high=1)
print(random_number)
print('------------------------------')
random_numbers = np.random.uniform(-1, 1, size=3)
print(random_numbers)
print('------------------------------')
random_array = np.random.uniform(-1, 1, size=(3,2))
print(random_array)                

0.22199317108973948
------------------------------
0.8707323061773764
------------------------------
-0.5865616893211472
------------------------------
0.8372218158758431
------------------------------
[-0.02317762  0.22348773  0.53181571]
------------------------------
[[ 0.03683598 -0.406399  ]
 [-0.62455754 -0.83851746]
 [ 0.47688059 -0.11738155]]


In [57]:
# Shuffling array using random generator
import numpy as np

random_generator = np.random.default_rng()
array = np.array([1, 3, 5, 7, 9, 11, 13])
print(f'Original Array: {array}')
random_generator.shuffle(array)
print(f'After first shuffle: {array}')
random_generator.shuffle(array)
print(f'After second shuffle: {array}')

Original Array: [ 1  3  5  7  9 11 13]
After first shuffle: [13  1  7  3  5 11  9]
After second shuffle: [ 1 13  7  3  9 11  5]


In [62]:
# Choosing random elements from a array
import numpy as np

range_generator = np.random.default_rng()
fruits = np.array(['apple', 'banana', 'cantalope', 'papaya', 'blueberry'])
choice = range_generator.choice(fruits)
print(f'Fruit chosen: {choice}')
choices = range_generator.choice(fruits, size=(4,4))
print(f'Fruits chosen: {choices}')

Fruit chosen: papaya
Fruits chosen: [['papaya' 'cantalope' 'papaya' 'blueberry']
 ['banana' 'apple' 'blueberry' 'cantalope']
 ['blueberry' 'blueberry' 'papaya' 'apple']
 ['banana' 'banana' 'cantalope' 'papaya']]
