In [5]:
# Numpy allows to filter the data set very efficiently
import numpy as np

ages = np.array([[25, 15, 18, 20, 31, 28, 45], [55, 16, 17, 24, 75, 60, 40]])
print(ages)

[[25 15 18 20 31 28 45]
 [55 16 17 24 75 60 40]]


In [7]:
# Filter all students with age < 18
teenages = ages[ages < 18]
print(teenages)

[15 16 17]


In [11]:
# Filter all students with age > 18 but less than 50
adults = ages[(ages >= 18) & (ages < 50)]
print(adults)

[25 18 20 31 28 45 24 40]


In [13]:
# Filter all students with age > 50
seniors = ages[ages >= 50]
print(seniors)

[55 75 60]


In [18]:
# Above method is called as boolean indexing and it doesnt preserve the shape of the array.
# To preserve the shape of the array we can use 'where()'
import numpy as np

ages = np.array([[25, 15, 18, 20, 31, 28, 45], [55, 16, 17, 24, 75, 60, 40]])
teenages = np.where(ages < 18, ages, 0)
print(teenages)
print('-----------------------------------')

adults = np.where(((ages >= 18) & (ages < 50)), ages, 0)
print(adults)
print('------------------------------------')

seniors = np.where(ages > 50, ages, 0)
print(seniors)


[[ 0 15  0  0  0  0  0]
 [ 0 16 17  0  0  0  0]]
-----------------------------------
[[25  0 18 20 31 28 45]
 [ 0  0  0 24  0  0 40]]
------------------------------------
[[ 0  0  0  0  0  0  0]
 [55  0  0  0 75 60  0]]
